version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: cherep-wallos_server_1
      APP_PORT: 50090

  server:
    image: bellamy/wallos:latest
    restart: on-failure
    user: "1000:1000"
    init: true