version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: cherep-wallos_wallos_1
      APP_PORT: 80

  wallos:
    image: bellamy/wallos:latest
    environment:
      TZ: "America/Chicago"
    volumes:
      - ${APP_DATA_DIR}/db:/var/www/html/db
      - ${APP_DATA_DIR}/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped